// mart-manage/src/components/layout/index.jsx
import React, { Component } from 'react'
import Header from './header';
import Footer from './footer';
import Slider from '../slider';

import "@/assets/css/reset.css";
import "@/assets/css/common.css";
import "@/assets/css/style.css";

class Layout extends Component {
  render() {
    return (
      <div className="wraper">
        <Header>
          <h2 className="mt10">校园超市</h2>
        </Header>
        <section className="content">
          <Slider>{this.props.children}</Slider>
        </section>
        <Footer></Footer>
      </div>
    )
  }
}
export default Layout

// mart-client/src/components/layout/index.vue
<template>
  <div class="wraper">
    <Header>
      <h4 class="mt5 text-center">校园超市</h4>
    </Header>
    <div class="content">
      <slot></slot>
    </div>
    <Footer></Footer>
  </div>
</template>

<script>
  import Header from './header';
  import Footer from './footer';
  export default {
    name: 'Layout',
    components: {
      Header,
      Footer,
    },
  };
</script>
